# Generated by Django 3.0.2 on 2020-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0004_remove_commits_pulltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='commits',
            name='pulltime',
            field=models.DateTimeField(default='2000-01-01 00:00'),
            preserve_default=False,
        ),
    ]
