# Generated by Django 3.0.2 on 2020-02-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0005_commits_pulltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commits',
            name='pulltime',
        ),
    ]
