# Generated by Django 3.0.2 on 2020-02-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0006_remove_commits_pulltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Docid', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Document', models.CharField(max_length=10000)),
                ('branch', models.CharField(default='master', max_length=50)),
            ],
        ),
    ]
