# Generated by Django 3.0.2 on 2020-02-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0007_pulls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commits',
            name='isdiff',
        ),
    ]
